In [5]:
import numpy as np
arr1 = np.linspace(0,20,21)
arr1

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20.])

In [6]:
arr2 = arr1[::2]
arr2

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [7]:
arr3 = arr1[3::3]
arr3

array([ 3.,  6.,  9., 12., 15., 18.])